//! Weight definitions for pallet-emergency-pause.
//!
//! These are placeholder weights. Real weights should be generated by running
//! the Substrate frame benchmarking suite against this pallet.

use frame_support::weights::Weight;

/// Weight functions needed for `pallet_emergency_pause`.
pub trait WeightInfo {
    fn propose_pause() -> Weight;
    fn propose_unpause() -> Weight;
    fn vote() -> Weight;
    fn emergency_pause() -> Weight;
    fn add_council_member() -> Weight;
    fn remove_council_member() -> Weight;
    fn cancel_proposal() -> Weight;
}

/// Default (conservative) weights used in unit tests and when no benchmarked
/// weights are available. All values are set to 10 000 reference-time units
/// plus one DB read and one DB write.
impl WeightInfo for () {
    fn propose_pause() -> Weight {
        Weight::from_parts(10_000, 0).saturating_add(Weight::from_parts(0, 0))
    }

    fn propose_unpause() -> Weight {
        Weight::from_parts(10_000, 0)
    }

    fn vote() -> Weight {
        Weight::from_parts(10_000, 0)
    }

    fn emergency_pause() -> Weight {
        Weight::from_parts(15_000, 0)
    }

    fn add_council_member() -> Weight {
        Weight::from_parts(10_000, 0)
    }

    fn remove_council_member() -> Weight {
        Weight::from_parts(10_000, 0)
    }

    fn cancel_proposal() -> Weight {
        Weight::from_parts(10_000, 0)
    }
}
